### PR TITLE
Upgrade From Upstream

### PR DESCRIPTION
**Pull request by sirwolfgang**
Rebase from upstream, resolving merge conflicts and updating a spec to test things.

If approved, I think rather then merging this in with master. Master should be force push replaced with this new rebased version, that has our custom commits on top.

### CODE REVIEW

**Comment by dalyons** [comment]
did you test it by pointing say, a server-api build at this branch? I think it will break with these changes, b/c the gemfile points to master. You'd prb have to pin the tag for the projects that you dont want to upgrade

**Comment by sirwolfgang** [comment]
@dalyons Working on that with now @sammilechman. There is seems to be an issue where our `utils` library breaks on this newer version. Something about the formatting of the request body.

Server-API is our target service for these bug fixes.

**Review by fzf — APPROVED** [review]

**Comment by fzf** [comment]
echoing @dalyons on ensuring that it works on server-api

**Comment by sirwolfgang** [comment]
While the upgrade does seem to fix some issues, it presents a different state than server api is expecting. I pushed up a test branch here: https://github.com/1debit/server-api/pull/419

@sammilechman found a workaround for our principle problem. So we no longer require this to move forward.

**Comment by sammilechman** [comment]
This is out of date and will require some work to get to a deployable state. Closing for now, as we found a way forward that doesn't require these changes, and this PR was causing some other issues that we didn't get the chance to diagnose/fix.

**Pull request closed without merging**
